# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "40f1c620279dad8f3b581cce8d7d33a5"
name = "BeninPay"
application_url = "https://beninpay.onrender.com/app"
embedded = true

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/app-uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/orders-paid"
  topics = [ "orders/paid" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/orders-create"
  topics = [ "orders/create" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_checkouts,write_orders,write_script_tags,read_script_tags,read_themes,write_themes"

[auth]
redirect_urls = [
  "https://beninpay.onrender.com/shopify/callback",
  "https://beninpay.onrender.com/auth/callback"
]

[pos]
embedded = false
